### ISSUE TITLE
编译出现如下错误

### ISSUE THREAD

**Issue by mybliss** [wenjiegit/Bull-Live-Server#2]
gcc -I. -I.  -c md5.c -o bin/md5.o
gcc -I. -I.  -c util_rbtree.c -o bin/util_rbtree.o
gcc -I. -I.  -c conhash_inter.c -o bin/conhash_inter.o
gcc -I. -I.  -c conhash_util.c -o bin/conhash_util.o
conhash_util.c: 在函数‘conhash_get_vnodes’中:
conhash_util.c:35: 警告：传递‘util_rbtree_mid_travel’的第 1 个实参时丢弃了指针目标类型的限定
util_rbtree.h:112: 附注：需要类型‘struct util_rbtree_t *’，但实参的类型为‘const struct util_rbtree_t *’
gcc -I. -I.  -c conhash.c -o bin/conhash.o
conhash.c: 在函数‘conhash_lookup’中:
conhash.c:104: 警告：传递‘util_rbtree_lookup’的第 1 个实参时丢弃了指针目标类型的限定
util_rbtree.h:74: 附注：需要类型‘struct util_rbtree_t *’，但实参的类型为‘const struct util_rbtree_t *’
ar -cqs bin/libconhash.a ./bin/md5.o ./bin/util_rbtree.o ./bin/conhash_inter.o ./bin/conhash_util.o ./bin/conhash.o
gcc -I. -I.  -c sample.c -o bin/sample.o
gcc -O -o bin/sample ./bin/sample.o -L. -L./bin -lconhash
        ............................        OK
run autoheader./autogen.sh: line 69: autoheader: command not found
    ............................        Failed!

**Comment by wenjiegit** [comment]
autotools 没有安装的原因
